apiVersion: batch/v1
kind: Job
metadata:
  namespace: team-1-namespace # Job under team-a namespace
  generateName: gpu-job-team-1-
  annotations:
    kueue.x-k8s.io/queue-name: team-1-lq # Point to the LocalQueue
spec:
  ttlSecondsAfterFinished: 60 # Job will be deleted after 60 seconds
  parallelism: 3 # This Job will have 3 replicas running at the same time
  completions: 3 # This Job requires 3 completions
  suspend: true # Set to true to allow Kueue to control the Job when it starts
  template:
    spec:
      nodeSelector:
        # cloud.google.com/gke-accelerator: "nvidia-tesla-t4" # Specify the GPU hardware
        cloud.google.com/gke-accelerator: nvidia-l4
      containers:
      - name: dummy-job
        image: gcr.io/k8s-staging-perf-tests/sleep:latest
        args: ["10s"] # Sleep for 10 seconds
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
            ephemeral-storage: "512Mi"
            nvidia.com/gpu: "0"
          limits:
            cpu: "500m"
            memory: "512Mi"
            ephemeral-storage: "512Mi"
            nvidia.com/gpu: "0"
      restartPolicy: Never